FROM resin/rpi-raspbian

RUN echo "deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi" >> /etc/apt/sources.list

RUN apt-get update -qq \
    && apt-get install python-pip python-pil git g++-4.6-arm-linux-gnueabihf

RUN pip install "django<2" Image==1.5.27 flask==1.0.2

RUN git clone https://github.com/gebart/python-v4l2capture.git

RUN mkdir -p /capture

WORKDIR /python-v4l2capture
RUN ./setup.py install
COPY app.py app.py
WORKDIR /capture
CMD python ../python-v4l2capture/app.py